/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controllers;

import Dao.Cadastro_mensagemDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cadastro_mensagem;

/**
 *
 * @author diego
 */
public class TelaConsultaMensagem extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaMensagem
     */
    public TelaConsultaMensagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaMensagem = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        txtId_mensagem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtMeio_Comunicacao = new javax.swing.JTextField();
        txtConteudo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCarregarCampos = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelaMensagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_mensagem", "categoria", "titulo", "meio_comunicacao", "conteudo"
            }
        ));
        jScrollPane1.setViewportView(TabelaMensagem);
        if (TabelaMensagem.getColumnModel().getColumnCount() > 0) {
            TabelaMensagem.getColumnModel().getColumn(0).setPreferredWidth(2);
            TabelaMensagem.getColumnModel().getColumn(1).setPreferredWidth(30);
            TabelaMensagem.getColumnModel().getColumn(2).setPreferredWidth(30);
            TabelaMensagem.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        txtId_mensagem.setEnabled(false);
        txtId_mensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_mensagemActionPerformed(evt);
            }
        });

        jLabel1.setText("id_mensagem");

        jLabel2.setText("categoria");

        jLabel3.setText("titulo");

        jLabel4.setText("meio_comunicacao");

        jLabel5.setText("conteudo");

        btnCarregarCampos.setText("Carregar");
        btnCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCamposActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMeio_Comunicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCarregarCampos)
                        .addGap(162, 162, 162)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId_mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListar)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId_mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluir)
                            .addComponent(btnCarregarCampos)
                            .addComponent(btnAlterar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMeio_Comunicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listaValores();
    }//GEN-LAST:event_btnListarActionPerformed


    private void txtId_mensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_mensagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_mensagemActionPerformed


    private void btnCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCamposActionPerformed
      CarregarCampos();
    }//GEN-LAST:event_btnCarregarCamposActionPerformed


    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       AlterarMensagem();
       listaValores();
    }//GEN-LAST:event_btnAlterarActionPerformed


    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ExcluirMensagem();
        listaValores();
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaMensagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaMensagem;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCarregarCampos;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtConteudo;
    private javax.swing.JTextField txtId_mensagem;
    private javax.swing.JTextField txtMeio_Comunicacao;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    private void listaValores() {
        try {

            Cadastro_mensagemDAO objCadastro_mensagemDAO = new Cadastro_mensagemDAO();

            DefaultTableModel model = (DefaultTableModel) TabelaMensagem.getModel();
            model.setNumRows(0);

            ArrayList<Cadastro_mensagem> lista = objCadastro_mensagemDAO.ListarMensagem();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_mensagem(),
                    lista.get(num).getCategoria(),
                    lista.get(num).getMeio_comunicacao(),
                    lista.get(num).getTitulo(),
                    lista.get(num).getConteudo()
                });

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Valores" + erro);
        }

    }

    private void CarregarCampos() {
        int setar = TabelaMensagem.getSelectedRow();

        txtId_mensagem.setText(TabelaMensagem.getModel().getValueAt(setar, 0).toString());
        txtCategoria.setText(TabelaMensagem.getModel().getValueAt(setar, 1).toString());
        txtTitulo.setText(TabelaMensagem.getModel().getValueAt(setar, 2).toString());
        txtMeio_Comunicacao.setText(TabelaMensagem.getModel().getValueAt(setar, 3).toString());
        txtConteudo.setText(TabelaMensagem.getModel().getValueAt(setar, 4).toString());

    }
    
    private void AlterarMensagem(){
        int id_mensagem;
        String titulo, categoria, conteudo, meio_comunicacao;
        
        id_mensagem = Integer.parseInt(txtId_mensagem.getText());
        titulo = txtTitulo.getText();
        categoria = txtCategoria.getText();
        meio_comunicacao = txtMeio_Comunicacao.getText();
        conteudo = txtConteudo.getText();
        
        Cadastro_mensagem objCadastro_mensagem = new Cadastro_mensagem();
        objCadastro_mensagem.setId_mensagem(id_mensagem);
        objCadastro_mensagem.setTitulo(titulo);
        objCadastro_mensagem.setCategoria(categoria);
        objCadastro_mensagem.setMeio_comunicacao(meio_comunicacao);
        objCadastro_mensagem.setConteudo(conteudo); 
        
        Cadastro_mensagemDAO objCadastro_mensagemDAO = new Cadastro_mensagemDAO();
        objCadastro_mensagemDAO.alterarMensagem(objCadastro_mensagem);
        
    }
    
        private void ExcluirMensagem(){
            int id_mensagem;
            id_mensagem = Integer.parseInt(txtId_mensagem.getText());
            
            Cadastro_mensagem objCadastro_mensagem = new Cadastro_mensagem();
            objCadastro_mensagem.setId_mensagem(id_mensagem);
            
            Cadastro_mensagemDAO objCadastro_mensagemDAO = new Cadastro_mensagemDAO();
            objCadastro_mensagemDAO.excluirMensagem(objCadastro_mensagem);
        }
    
    
    
}
