/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controllers;

import Dao.Cadastro_mensagemDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cadastro_mensagem;

/**
 *
 * @author diego
 */
public class TelaConsultaMensagem extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaMensagem
     */
    public TelaConsultaMensagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaMensagem = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelaMensagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_mensagem", "categoria", "titulo", "meio_comunicacao", "conteudo"
            }
        ));
        jScrollPane1.setViewportView(TabelaMensagem);
        if (TabelaMensagem.getColumnModel().getColumnCount() > 0) {
            TabelaMensagem.getColumnModel().getColumn(0).setPreferredWidth(2);
            TabelaMensagem.getColumnModel().getColumn(1).setPreferredWidth(30);
            TabelaMensagem.getColumnModel().getColumn(2).setPreferredWidth(30);
            TabelaMensagem.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        btnListar.setBackground(new java.awt.Color(255, 183, 74));
        btnListar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("Listar");
        btnListar.setBorderPainted(false);
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 183, 74));

        btnVoltar.setBackground(new java.awt.Color(255, 183, 74));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorderPainted(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(255, 183, 74));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Mensagens Cadastradas");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnVoltar)
                .addGap(29, 29, 29)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(527, Short.MAX_VALUE)
                .addComponent(btnListar)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnListar)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents





    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listaValores();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaMensagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaMensagem;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private void listaValores() {
        try {

            Cadastro_mensagemDAO objCadastro_mensagemDAO = new Cadastro_mensagemDAO();

            DefaultTableModel model = (DefaultTableModel) TabelaMensagem.getModel();
            model.setNumRows(0);

            ArrayList<Cadastro_mensagem> lista = objCadastro_mensagemDAO.ListarMensagem();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_mensagem(),
                    lista.get(num).getCategoria(),
                    lista.get(num).getMeio_comunicacao(),
                    lista.get(num).getTitulo(),
                    lista.get(num).getConteudo()
                });

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Valores" + erro);
        }

    }
/*
    private void CarregarCampos() {
        int setar = TabelaMensagem.getSelectedRow();

        txtId_mensagem.setText(TabelaMensagem.getModel().getValueAt(setar, 0).toString());
        txtCategoria.setText(TabelaMensagem.getModel().getValueAt(setar, 1).toString());
        txtTitulo.setText(TabelaMensagem.getModel().getValueAt(setar, 2).toString());
        txtMeio_Comunicacao.setText(TabelaMensagem.getModel().getValueAt(setar, 3).toString());
        txtConteudo.setText(TabelaMensagem.getModel().getValueAt(setar, 4).toString());

    }

    
    private void AlterarMensagem(){
        int id_mensagem;
        String titulo, categoria, conteudo, meio_comunicacao;
        
        id_mensagem = Integer.parseInt(txtId_mensagem.getText());
        titulo = txtTitulo.getText();
        categoria = txtCategoria.getText();
        meio_comunicacao = txtMeio_Comunicacao.getText();
        conteudo = txtConteudo.getText();
        
        Cadastro_mensagem objCadastro_mensagem = new Cadastro_mensagem();
        objCadastro_mensagem.setId_mensagem(id_mensagem);
        objCadastro_mensagem.setTitulo(titulo);
        objCadastro_mensagem.setCategoria(categoria);
        objCadastro_mensagem.setMeio_comunicacao(meio_comunicacao);
        objCadastro_mensagem.setConteudo(conteudo); 
        
        Cadastro_mensagemDAO objCadastro_mensagemDAO = new Cadastro_mensagemDAO();
        objCadastro_mensagemDAO.alterarMensagem(objCadastro_mensagem);
        
    }
    
        private void ExcluirMensagem(){
            int id_mensagem;
            id_mensagem = Integer.parseInt(txtId_mensagem.getText());
            
            Cadastro_mensagem objCadastro_mensagem = new Cadastro_mensagem();
            objCadastro_mensagem.setId_mensagem(id_mensagem);
            
            Cadastro_mensagemDAO objCadastro_mensagemDAO = new Cadastro_mensagemDAO();
            objCadastro_mensagemDAO.excluirMensagem(objCadastro_mensagem);
        }
    
    */
    
}
